# Production logging profile
logging.level.root=INFO
logging.level.edu.eci.dosw.techcup_futbol=INFO
spring.data.mongodb.uri=${MONGODB_URI_PROD:${MONGODB_URI:mongodb://localhost:27017/techcup_futbol_prod}}
